### ISSUE TITLE
Error message from addon when called by script.module.metadatautils

### ISSUE THREAD

**Issue by berkhornet** [kodi-community-addons/script.module.thetvdb#11]
I've getting this error frequently (but not always) from script.module.thetvdb when updating PVR artwork in script.module.metadatautils. An example from the kodi log (looking up TV Show Cold River Cash):

2022-07-29 10:04:50.804 T:1792     INFO <general>: script.module.metadatautils --> pvrart lookup for title: cold river cash - TVDB result: 276670
2022-07-29 10:04:50.943 T:1792    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: string indices must be integers
                                                   Traceback (most recent call last):
                                                     File "C:\Users\mickr\AppData\Roaming\Kodi\addons\script.skin.helper.service\resources\lib\context_pvr.py", line 28, in <module>
                                                       metadatautils.pvr_artwork_options(title, channel, genre)
                                                     File "C:\Users\mickr\AppData\Roaming\Kodi\addons\script.module.metadatautils\lib\metadatautils.py", line 152, in pvr_artwork_options
                                                       return self.pvrart.pvr_artwork_options(title, channel, genre)
                                                     File "C:\Users\mickr\AppData\Roaming\Kodi\addons\script.module.metadatautils\lib\helpers\pvrartwork.py", line 267, in pvr_artwork_options
                                                       self.get_pvr_artwork(title=title, channel=channel, genre=genre, ignore_cache=True, manual_select=True)
                                                     File "C:\Users\mickr\AppData\Roaming\Kodi\addons\script.module.metadatautils\lib\helpers\pvrartwork.py", line 153, in get_pvr_artwork
                                                       details = extend_dict(details, self._mutils.thetvdb.get_series(tvdb_match))
                                                     File "C:\Users\mickr\AppData\Roaming\Kodi\addons\script.module.simplecache\lib\simplecache.py", line 304, in decorated
                                                       result = func(*args, **kwargs)
                                                     File "C:\Users\mickr\AppData\Roaming\Kodi\addons\script.module.thetvdb\lib\thetvdb.py", line 165, in get_series
                                                       return self._map_series_data(seriesinfo)
                                                     File "C:\Users\mickr\AppData\Roaming\Kodi\addons\script.module.thetvdb\lib\thetvdb.py", line 555, in _map_series_data
                                                       result["cast.%s.tvdbname" % count] = item["name"]
                                                   TypeError: string indices must be integers
                                                   -->End of Python script error report<--
                                                   
2022-07-29 10:04:51.173 T:1792     INFO <general>: script.module.thetvdb --> Exited
2022-07-29 10:04:51.173 T:1792     INFO <general>: script.module.metadatautils --> Exited

Because I'm primarily interested in the artwork, I have created a workaround for error by commenting out the following lines 552-557 in lib\thetvdb.py:

#if cast:
                #for count, item in enumerate(cast):
                    #if count < 4:
                        #result["cast.%s.tvdbname" % count] = item["name"]
                        #result["cast.%s.tvdbrole" % count] = item["role"]
                        #result["cast.%s.tvdbthumb" % count] = "https://artworks.thetvdb.com/banners/%s" % item["image"]

**Comment by Angelinas1** [comment]
https://github.com/kodi-community-addons/script.module.thetvdb/commit/c6f987be07b9ff3c2e142711432a542d8f960049

**Comment by berkhornet** [comment]
Many thanks.

Mick
________________________________
