### ISSUE TITLE
script.tv.show.next.aired Exception in resources.lib.main_module ! --> global name '_log_msg' is not defined

### ISSUE THREAD

**Issue by mgonzales71** [kodi-community-addons/script.module.thetvdb#8]
Started seeing the following error using Kodi 18/Leia nightly builds on Win64:

```
22:34:40.957 T:12236   DEBUG: script.tv.show.next.aired --> Traceback (most recent call last):
                                              File "C:\Users\Mario\AppData\Roaming\Kodi\addons\script.tv.show.next.aired\resources\lib\main_module.py", line 36, in __init__
                                                getattr(self, action)(action_param)
                                              File "C:\Users\Mario\AppData\Roaming\Kodi\addons\script.tv.show.next.aired\resources\lib\main_module.py", line 285, in main
                                                eps_list = self.get_nextaired_listing(include_last_episode=want_yesterday)
                                              File "C:\Users\Mario\AppData\Roaming\Kodi\addons\script.tv.show.next.aired\resources\lib\main_module.py", line 303, in get_nextaired_listing
                                                single_episode_per_show=False, include_last_episode=include_last_episode)
                                              File "C:\Users\Mario\AppData\Roaming\Kodi\addons\script.module.thetvdb\lib\thetvdb.py", line 450, in get_kodi_unaired_episodes
                                                episodes.append(self.get_last_episode_for_series(serieid))
                                              File "C:\Users\Mario\AppData\Roaming\Kodi\addons\script.module.simplecache\lib\simplecache.py", line 284, in decorated
                                                result = func(*args, **kwargs)
                                              File "C:\Users\Mario\AppData\Roaming\Kodi\addons\script.module.thetvdb\lib\thetvdb.py", line 250, in get_last_episode_for_series
                                                return self.get_episode(highest_eps[1])
                                              File "C:\Users\Mario\AppData\Roaming\Kodi\addons\script.module.simplecache\lib\simplecache.py", line 284, in decorated
                                                result = func(*args, **kwargs)
                                              File "C:\Users\Mario\AppData\Roaming\Kodi\addons\script.module.thetvdb\lib\thetvdb.py", line 154, in get_episode
                                                episode = self._map_episode_data(episode, seriesdetails)
                                              File "C:\Users\Mario\AppData\Roaming\Kodi\addons\script.module.thetvdb\lib\thetvdb.py", line 479, in _map_episode_data
                                                result["airdate"] = self._get_local_date(episode_details["firstAired"])
                                              File "C:\Users\Mario\AppData\Roaming\Kodi\addons\script.module.thetvdb\lib\thetvdb.py", line 744, in _get_local_date
                                                _log_msg("Exception in _get_local_date: %s" % exc)
                                            NameError: global name '_log_msg' is not defined
22:34:40.957 T:12236 WARNING: script.tv.show.next.aired --> Exception in resources.lib.main_module ! --> global name '_log_msg' is not defined
22:34:40.957 T:12236   DEBUG: script.tv.show.next.aired --> MainModule exited
22:34:40.958 T:12236   DEBUG: Skin Helper Simplecache --> Closed
22:34:40.958 T:12236   DEBUG: script.module.thetvdb --> Exited
22:34:40.961 T:12236    INFO: CPythonInvoker(74, C:\Users\Mario\AppData\Roaming\Kodi\addons\script.tv.show.next.aired\default.py): script successfully run
22:34:40.974 T:12236    INFO: Python script stopped
22:34:40.974 T:12236   DEBUG: Thread LanguageInvoker 12236 terminating

```

Now I am by NO means a python coder - but I was able to get things "working" again with the following (bad I am sure) hack...

Changed line 744 of script.module.thetvdb\lib\thetvdb.py

from

`            _log_msg("Exception in _get_local_date: %s" % exc)`

to

`            return datestr`

obviously I am sure that this doesn't fix anything just skips logging an error and avoiding whatever was throwing the exception when trying to log the well exception :-)

**Comment by mgonzales71** [comment]
modded file:

[thetvdb.py.txt](https://github.com/marcelveldt/script.module.thetvdb/files/1859101/thetvdb.py.txt)


It at least now let's me bring up the guide and from what I can tell the info it correct.

**Comment by marcelveldt** [comment]
Hi Mario,

The bug is fixed just now in the code. Now I'm curious if the underlying issue is also gone now.

**Comment by mgonzales71** [comment]
Yes seems to work better now but I did see the following in the log just as an FYI

```
09:19:32.626 T:16416   DEBUG: CPythonInvoker(250, C:\Users\Mario\AppData\Roaming\Kodi\addons\script.tv.show.next.aired\default.py): entering source directory C:\Users\Mario\AppData\Roaming\Kodi\addons\script.tv.show.next.aired
09:19:32.626 T:16416   DEBUG: CPythonInvoker(250, C:\Users\Mario\AppData\Roaming\Kodi\addons\script.tv.show.next.aired\default.py): instantiating addon using automatically obtained id of "script.tv.show.next.aired" dependent on version 2.1.0 of the xbmc.python api
09:19:34.003 T:16416   DEBUG: Skin Helper Simplecache --> Initialized
09:19:34.004 T:16416   DEBUG: script.module.thetvdb --> Initialized
09:19:34.016 T:16416   DEBUG: script.tv.show.next.aired --> MainModule called with action: main - parameter:
09:19:34.019 T:16416   DEBUG: JSONRPC: Incoming request: { "jsonrpc": "2.0", "method" : "VideoLibrary.GetTvShows", "params": {"properties": [ "file", "title", "year", "imdbnumber", "art", "genre", "cast", "studio", "uniqueid" ] }, "id":1 }
09:19:35.756 T:4484   DEBUG: Activating window ID: 13002
09:19:36.083 T:4484   DEBUG: ------ Window Deinit (MyPrograms.xml) ------

[several Kodi 18 settings parse errors, Leia and settings 2.0 migration is a hot mess]

09:19:36.263 T:16416   ERROR: EXCEPTION: Non-Existent Control 212
09:19:36.265 T:16416   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.RuntimeError'>
                                            Error Contents: Non-Existent Control 212
                                            Traceback (most recent call last):
                                              File "C:\Users\Mario\AppData\Roaming\Kodi\addons\script.tv.show.next.aired\resources\lib\next_aired_dialog.py", line 53, in onInit
                                                self.fill_containers()
                                              File "C:\Users\Mario\AppData\Roaming\Kodi\addons\script.tv.show.next.aired\resources\lib\next_aired_dialog.py", line 109, in fill_containers
                                                self.getControl(c).reset()
                                            RuntimeError: Non-Existent Control 212
                                            -->End of Python script error report<--

```
